### ISSUE TITLE
ピン追加機能の実装

### ISSUE THREAD

**Issue by e1b21115** [e1b21115/Fork_2024_L#22]
- #### やってほしいこと
管理者画面でピンを任意の場所にピンを追加できるようにする

- #### やらなくてもいいこと

**Comment by naoya0117** [comment]
@e1b21115 
https://github.com/e1b21115/Fork_2024_L/issues/9

このissueで実装した機能かと思います。
フォームに座標取得機能を実装しています。
ご確認よろしくお願いいたします。

**Comment by e1b21115** [comment]
確認したいけどurlが分かんなくて...
どこにアクセスしたらいいですか？

**Comment by naoya0117** [comment]
8000番ポート、
.env.exampleを.envにコピーして
コンテナを再起動すれば見れるはず

**Comment by e1b21115** [comment]
了解です。見ときます

**Comment by e1b21115** [comment]
/markersに飛んだら404吐かれたけど...

**Comment by naoya0117** [comment]
まじかー

**Comment by naoya0117** [comment]
404ページ？それともapiのエラー？

**Comment by naoya0117** [comment]
@e1b21115 
404ページ？それともapiのエラー？

**Comment by naoya0117** [comment]
@e1b21115 
多分、.env.exampleを.envにコピーしてコンテナ再起動すれば行ける

**Comment by e1b21115** [comment]
確認できました。イシューとじときます
